/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-26 at 01:47:53 UTC 
 * Modify at your own risk.
 */

package com.littleflash.backend.flashendpoint;

/**
 * Service definition for Flashendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FlashendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Flashendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the flashendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://little-flash.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "flashendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Flashendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Flashendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getFlash".
   *
   * This request holds the parameters needed by the the flashendpoint server.  After setting any
   * optional parameters, call the {@link GetFlash#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetFlash getFlash(java.lang.Long id) throws java.io.IOException {
    GetFlash result = new GetFlash(id);
    initialize(result);
    return result;
  }

  public class GetFlash extends FlashendpointRequest<com.littleflash.backend.flashendpoint.model.Flash> {

    private static final String REST_PATH = "flash/{id}";

    /**
     * Create a request for the method "getFlash".
     *
     * This request holds the parameters needed by the the flashendpoint server.  After setting any
     * optional parameters, call the {@link GetFlash#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetFlash#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetFlash(java.lang.Long id) {
      super(Flashendpoint.this, "GET", REST_PATH, null, com.littleflash.backend.flashendpoint.model.Flash.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetFlash setAlt(java.lang.String alt) {
      return (GetFlash) super.setAlt(alt);
    }

    @Override
    public GetFlash setFields(java.lang.String fields) {
      return (GetFlash) super.setFields(fields);
    }

    @Override
    public GetFlash setKey(java.lang.String key) {
      return (GetFlash) super.setKey(key);
    }

    @Override
    public GetFlash setOauthToken(java.lang.String oauthToken) {
      return (GetFlash) super.setOauthToken(oauthToken);
    }

    @Override
    public GetFlash setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetFlash) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetFlash setQuotaUser(java.lang.String quotaUser) {
      return (GetFlash) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetFlash setUserIp(java.lang.String userIp) {
      return (GetFlash) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetFlash setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetFlash set(String parameterName, Object value) {
      return (GetFlash) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertFlash".
   *
   * This request holds the parameters needed by the the flashendpoint server.  After setting any
   * optional parameters, call the {@link InsertFlash#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.littleflash.backend.flashendpoint.model.Flash}
   * @return the request
   */
  public InsertFlash insertFlash(com.littleflash.backend.flashendpoint.model.Flash content) throws java.io.IOException {
    InsertFlash result = new InsertFlash(content);
    initialize(result);
    return result;
  }

  public class InsertFlash extends FlashendpointRequest<com.littleflash.backend.flashendpoint.model.Flash> {

    private static final String REST_PATH = "flash";

    /**
     * Create a request for the method "insertFlash".
     *
     * This request holds the parameters needed by the the flashendpoint server.  After setting any
     * optional parameters, call the {@link InsertFlash#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertFlash#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.littleflash.backend.flashendpoint.model.Flash}
     * @since 1.13
     */
    protected InsertFlash(com.littleflash.backend.flashendpoint.model.Flash content) {
      super(Flashendpoint.this, "POST", REST_PATH, content, com.littleflash.backend.flashendpoint.model.Flash.class);
    }

    @Override
    public InsertFlash setAlt(java.lang.String alt) {
      return (InsertFlash) super.setAlt(alt);
    }

    @Override
    public InsertFlash setFields(java.lang.String fields) {
      return (InsertFlash) super.setFields(fields);
    }

    @Override
    public InsertFlash setKey(java.lang.String key) {
      return (InsertFlash) super.setKey(key);
    }

    @Override
    public InsertFlash setOauthToken(java.lang.String oauthToken) {
      return (InsertFlash) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertFlash setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertFlash) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertFlash setQuotaUser(java.lang.String quotaUser) {
      return (InsertFlash) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertFlash setUserIp(java.lang.String userIp) {
      return (InsertFlash) super.setUserIp(userIp);
    }

    @Override
    public InsertFlash set(String parameterName, Object value) {
      return (InsertFlash) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listFlash".
   *
   * This request holds the parameters needed by the the flashendpoint server.  After setting any
   * optional parameters, call the {@link ListFlash#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListFlash listFlash() throws java.io.IOException {
    ListFlash result = new ListFlash();
    initialize(result);
    return result;
  }

  public class ListFlash extends FlashendpointRequest<com.littleflash.backend.flashendpoint.model.CollectionResponseFlash> {

    private static final String REST_PATH = "flash";

    /**
     * Create a request for the method "listFlash".
     *
     * This request holds the parameters needed by the the flashendpoint server.  After setting any
     * optional parameters, call the {@link ListFlash#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListFlash#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListFlash() {
      super(Flashendpoint.this, "GET", REST_PATH, null, com.littleflash.backend.flashendpoint.model.CollectionResponseFlash.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListFlash setAlt(java.lang.String alt) {
      return (ListFlash) super.setAlt(alt);
    }

    @Override
    public ListFlash setFields(java.lang.String fields) {
      return (ListFlash) super.setFields(fields);
    }

    @Override
    public ListFlash setKey(java.lang.String key) {
      return (ListFlash) super.setKey(key);
    }

    @Override
    public ListFlash setOauthToken(java.lang.String oauthToken) {
      return (ListFlash) super.setOauthToken(oauthToken);
    }

    @Override
    public ListFlash setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListFlash) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListFlash setQuotaUser(java.lang.String quotaUser) {
      return (ListFlash) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListFlash setUserIp(java.lang.String userIp) {
      return (ListFlash) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListFlash setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListFlash setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListFlash set(String parameterName, Object value) {
      return (ListFlash) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeFlash".
   *
   * This request holds the parameters needed by the the flashendpoint server.  After setting any
   * optional parameters, call the {@link RemoveFlash#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveFlash removeFlash(java.lang.Long id) throws java.io.IOException {
    RemoveFlash result = new RemoveFlash(id);
    initialize(result);
    return result;
  }

  public class RemoveFlash extends FlashendpointRequest<Void> {

    private static final String REST_PATH = "flash/{id}";

    /**
     * Create a request for the method "removeFlash".
     *
     * This request holds the parameters needed by the the flashendpoint server.  After setting any
     * optional parameters, call the {@link RemoveFlash#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveFlash#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveFlash(java.lang.Long id) {
      super(Flashendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveFlash setAlt(java.lang.String alt) {
      return (RemoveFlash) super.setAlt(alt);
    }

    @Override
    public RemoveFlash setFields(java.lang.String fields) {
      return (RemoveFlash) super.setFields(fields);
    }

    @Override
    public RemoveFlash setKey(java.lang.String key) {
      return (RemoveFlash) super.setKey(key);
    }

    @Override
    public RemoveFlash setOauthToken(java.lang.String oauthToken) {
      return (RemoveFlash) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveFlash setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveFlash) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveFlash setQuotaUser(java.lang.String quotaUser) {
      return (RemoveFlash) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveFlash setUserIp(java.lang.String userIp) {
      return (RemoveFlash) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveFlash setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveFlash set(String parameterName, Object value) {
      return (RemoveFlash) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateFlash".
   *
   * This request holds the parameters needed by the the flashendpoint server.  After setting any
   * optional parameters, call the {@link UpdateFlash#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.littleflash.backend.flashendpoint.model.Flash}
   * @return the request
   */
  public UpdateFlash updateFlash(com.littleflash.backend.flashendpoint.model.Flash content) throws java.io.IOException {
    UpdateFlash result = new UpdateFlash(content);
    initialize(result);
    return result;
  }

  public class UpdateFlash extends FlashendpointRequest<com.littleflash.backend.flashendpoint.model.Flash> {

    private static final String REST_PATH = "flash";

    /**
     * Create a request for the method "updateFlash".
     *
     * This request holds the parameters needed by the the flashendpoint server.  After setting any
     * optional parameters, call the {@link UpdateFlash#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateFlash#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.littleflash.backend.flashendpoint.model.Flash}
     * @since 1.13
     */
    protected UpdateFlash(com.littleflash.backend.flashendpoint.model.Flash content) {
      super(Flashendpoint.this, "PUT", REST_PATH, content, com.littleflash.backend.flashendpoint.model.Flash.class);
    }

    @Override
    public UpdateFlash setAlt(java.lang.String alt) {
      return (UpdateFlash) super.setAlt(alt);
    }

    @Override
    public UpdateFlash setFields(java.lang.String fields) {
      return (UpdateFlash) super.setFields(fields);
    }

    @Override
    public UpdateFlash setKey(java.lang.String key) {
      return (UpdateFlash) super.setKey(key);
    }

    @Override
    public UpdateFlash setOauthToken(java.lang.String oauthToken) {
      return (UpdateFlash) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateFlash setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateFlash) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateFlash setQuotaUser(java.lang.String quotaUser) {
      return (UpdateFlash) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateFlash setUserIp(java.lang.String userIp) {
      return (UpdateFlash) super.setUserIp(userIp);
    }

    @Override
    public UpdateFlash set(String parameterName, Object value) {
      return (UpdateFlash) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Flashendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Flashendpoint}. */
    @Override
    public Flashendpoint build() {
      return new Flashendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FlashendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFlashendpointRequestInitializer(
        FlashendpointRequestInitializer flashendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(flashendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
