/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-22 at 23:57:39 UTC 
 * Modify at your own risk.
 */

package com.littleflash.backend.flashendpoint.model;

/**
 * Model definition for Flash.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the flashendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Flash extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime flashDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String itemId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String itemType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String price;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String shopId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userEmail;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFlashDate() {
    return flashDate;
  }

  /**
   * @param flashDate flashDate or {@code null} for none
   */
  public Flash setFlashDate(com.google.api.client.util.DateTime flashDate) {
    this.flashDate = flashDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getItemId() {
    return itemId;
  }

  /**
   * @param itemId itemId or {@code null} for none
   */
  public Flash setItemId(java.lang.String itemId) {
    this.itemId = itemId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getItemType() {
    return itemType;
  }

  /**
   * @param itemType itemType or {@code null} for none
   */
  public Flash setItemType(java.lang.String itemType) {
    this.itemType = itemType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Flash setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPrice() {
    return price;
  }

  /**
   * @param price price or {@code null} for none
   */
  public Flash setPrice(java.lang.String price) {
    this.price = price;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getShopId() {
    return shopId;
  }

  /**
   * @param shopId shopId or {@code null} for none
   */
  public Flash setShopId(java.lang.String shopId) {
    this.shopId = shopId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserEmail() {
    return userEmail;
  }

  /**
   * @param userEmail userEmail or {@code null} for none
   */
  public Flash setUserEmail(java.lang.String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  @Override
  public Flash set(String fieldName, Object value) {
    return (Flash) super.set(fieldName, value);
  }

  @Override
  public Flash clone() {
    return (Flash) super.clone();
  }

}
